[frontend]
frontend_server ansible_host=52.54.77.28

[backend]
backend_server ansible_host=10.0.2.110

[worker]
worker_server ansible_host=10.0.2.142

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/Desktop/yahali/Devops/key-for-aws/yahali-test-key.pem
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[internal:children]
backend
worker

[internal:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q ubuntu@52.54.77.28 -o StrictHostKeyChecking=no -i ~/Desktop/yahali/Devops/key-for-aws/yahali-test-key.pem" -o StrictHostKeyChecking=no'